export const UPDATE_CART_QUANTITY = "UPDATE_CART_QUANTITY";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const INITIALIZE = "INITIALIZE";
